#spring.application.name=qiancode
server:
  servlet:
    context-path: /api

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/amigoscodedemo
    username: postgres
    password: password
    pool-size: 30
#
#spring:
#  flyway:
#    default-schema: markov_demo
#    locations: classpath:db/migration
#    baseline-on-migrate: true

